//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubros
    {
        public Rubros()
        {
            this.Adicionales = new HashSet<Adicionales>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
    
        public virtual ICollection<Adicionales> Adicionales { get; set; }
    }
}
