//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicionales
    {
        public Adicionales()
        {
            this.AdicionalesItems = new HashSet<AdicionalesItems>();
            this.CostoAdicionales = new HashSet<CostoAdicionales>();
            this.TipoCateringAdicional = new HashSet<TipoCateringAdicional>();
            this.TipoServicioAdicional = new HashSet<TipoServicioAdicional>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> RubroId { get; set; }
        public Nullable<double> Precio { get; set; }
        public int EstadoId { get; set; }
        public string RequiereCantidad { get; set; }
        public string RequiereCantidadRango { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<int> LocacionId { get; set; }
        public string SoloMayores { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual UnidadesNegocios UnidadesNegocios { get; set; }
        public virtual ICollection<AdicionalesItems> AdicionalesItems { get; set; }
        public virtual ICollection<CostoAdicionales> CostoAdicionales { get; set; }
        public virtual ICollection<TipoCateringAdicional> TipoCateringAdicional { get; set; }
        public virtual ICollection<TipoServicioAdicional> TipoServicioAdicional { get; set; }
    }
}
