//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuestos
    {
        public Impuestos()
        {
            this.ComprobantesProveedores_Detalles = new HashSet<ComprobantesProveedores_Detalles>();
            this.TipoComprobante_Impuestos = new HashSet<TipoComprobante_Impuestos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Porcentaje { get; set; }
    
        public virtual ICollection<ComprobantesProveedores_Detalles> ComprobantesProveedores_Detalles { get; set; }
        public virtual ICollection<TipoComprobante_Impuestos> TipoComprobante_Impuestos { get; set; }
    }
}
