//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_Unidades
    {
        public INVENTARIO_Unidades()
        {
            this.INVENTARIO_Producto = new HashSet<INVENTARIO_Producto>();
            this.INVENTARIO_Producto1 = new HashSet<INVENTARIO_Producto>();
            this.INVENTARIO_Recetas = new HashSet<INVENTARIO_Recetas>();
            this.INVENTARIO_Requerimiento_Detalle = new HashSet<INVENTARIO_Requerimiento_Detalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
    
        public virtual ICollection<INVENTARIO_Producto> INVENTARIO_Producto { get; set; }
        public virtual ICollection<INVENTARIO_Producto> INVENTARIO_Producto1 { get; set; }
        public virtual ICollection<INVENTARIO_Recetas> INVENTARIO_Recetas { get; set; }
        public virtual ICollection<INVENTARIO_Requerimiento_Detalle> INVENTARIO_Requerimiento_Detalle { get; set; }
    }
}
