//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocacionesValorAnio
    {
        public int Id { get; set; }
        public int LocacionId { get; set; }
        public int Anio { get; set; }
        public double Costo { get; set; }
    
        public virtual Locaciones Locaciones { get; set; }
    }
}
