//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCredito_Detalle
    {
        public int Id { get; set; }
        public int NotaCreditoId { get; set; }
        public int TipoMovimientoId { get; set; }
        public double Importe { get; set; }
    
        public virtual NotaCreditos NotaCreditos { get; set; }
    }
}
