//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerUsuarios
    {
        public string ApellidoNombre { get; set; }
        public string UserName { get; set; }
        public string Mail { get; set; }
        public string Nombre { get; set; }
        public int EstadoId { get; set; }
        public string Descripcion { get; set; }
        public int EmpleadoId { get; set; }
        public int Id { get; set; }
    }
}
