//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerPrecioCostoTecnica
    {
        public int Id { get; set; }
        public string Servicio { get; set; }
        public string Segmento { get; set; }
        public string RazonSocial { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public string Dia { get; set; }
        public double Precio { get; set; }
        public Nullable<double> Costo { get; set; }
    }
}
