//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibos
    {
        public Recibos()
        {
            this.ReciboEventoPresupuesto = new HashSet<ReciboEventoPresupuesto>();
        }
    
        public int Id { get; set; }
        public string NroRecibo { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public string Concepto { get; set; }
        public System.DateTime FechaCreate { get; set; }
        public double Importe { get; set; }
        public int FormadePagoId { get; set; }
        public Nullable<System.DateTime> FechaUpdate { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.DateTime> FechaDelete { get; set; }
    
        public virtual FormasdePago FormasdePago { get; set; }
        public virtual ICollection<ReciboEventoPresupuesto> ReciboEventoPresupuesto { get; set; }
    }
}
