//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteComprobantes
    {
        public int Id { get; set; }
        public long NroComprobante { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<double> MontoFactura { get; set; }
        public string Descripcion { get; set; }
        public string RazonSocial { get; set; }
        public string Cuenta { get; set; }
        public double NETO { get; set; }
        public string TipoImpuesto { get; set; }
        public double IMPUESTO { get; set; }
        public double IMPUESTOINTERNO { get; set; }
        public string FormadePago { get; set; }
        public string CC { get; set; }
        public string Leyenda { get; set; }
        public string Codigo { get; set; }
    }
}
