//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComprobante_Impuestos
    {
        public int Id { get; set; }
        public int TipoComprobanteId { get; set; }
        public int ImpuestoId { get; set; }
    
        public virtual Impuestos Impuestos { get; set; }
        public virtual TipoComprobantes TipoComprobantes { get; set; }
    }
}
