//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComprobantes
    {
        public TipoComprobantes()
        {
            this.ComprobantesProveedores = new HashSet<ComprobantesProveedores>();
            this.TipoComprobante_Impuestos = new HashSet<TipoComprobante_Impuestos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ComprobantesProveedores> ComprobantesProveedores { get; set; }
        public virtual ICollection<TipoComprobante_Impuestos> TipoComprobante_Impuestos { get; set; }
    }
}
