//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencias
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public int BancoId { get; set; }
        public string NroTransferencia { get; set; }
        public double Importe { get; set; }
        public string NombreArchivo { get; set; }
        public byte[] Comprobante { get; set; }
        public string ComprobanteExtension { get; set; }
        public System.DateTime FechaTransferencia { get; set; }
        public System.DateTime FechaCreate { get; set; }
        public Nullable<System.DateTime> FechaUpdate { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.DateTime> FechaDelete { get; set; }
    
        public virtual Bancos Bancos { get; set; }
    }
}
