//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesNegocios
    {
        public UnidadesNegocios()
        {
            this.Adicionales = new HashSet<Adicionales>();
            this.ComprobantesProveedores_Detalles = new HashSet<ComprobantesProveedores_Detalles>();
            this.Intermediarios = new HashSet<Intermediarios>();
            this.Productos = new HashSet<Productos>();
            this.TipoCatering = new HashSet<TipoCatering>();
            this.TipoServicios = new HashSet<TipoServicios>();
            this.UnidadesNegocios_Proveedores = new HashSet<UnidadesNegocios_Proveedores>();
            this.UnidadesNegocios_TipoMovimientos = new HashSet<UnidadesNegocios_TipoMovimientos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Adicionales> Adicionales { get; set; }
        public virtual ICollection<ComprobantesProveedores_Detalles> ComprobantesProveedores_Detalles { get; set; }
        public virtual ICollection<Intermediarios> Intermediarios { get; set; }
        public virtual ICollection<Productos> Productos { get; set; }
        public virtual ICollection<TipoCatering> TipoCatering { get; set; }
        public virtual ICollection<TipoServicios> TipoServicios { get; set; }
        public virtual ICollection<UnidadesNegocios_Proveedores> UnidadesNegocios_Proveedores { get; set; }
        public virtual ICollection<UnidadesNegocios_TipoMovimientos> UnidadesNegocios_TipoMovimientos { get; set; }
    }
}
