//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbientacionCI
    {
        public AmbientacionCI()
        {
            this.CostosPaquetesCIAmbientacion = new HashSet<CostosPaquetesCIAmbientacion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool Flete { get; set; }
        public int EstadoId { get; set; }
    
        public virtual ICollection<CostosPaquetesCIAmbientacion> CostosPaquetesCIAmbientacion { get; set; }
    }
}
