//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        public Bancos()
        {
            this.Cheques = new HashSet<Cheques>();
            this.Transferencias = new HashSet<Transferencias>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Cheques> Cheques { get; set; }
        public virtual ICollection<Transferencias> Transferencias { get; set; }
    }
}
