//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasItem
    {
        public CategoriasItem()
        {
            this.Familias = new HashSet<Familias>();
            this.Items = new HashSet<Items>();
            this.TipoBarraCategoriaItem = new HashSet<TipoBarraCategoriaItem>();
            this.TipoCateringTiempoProductoItem = new HashSet<TipoCateringTiempoProductoItem>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CategoriaItemPadreId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual ICollection<Familias> Familias { get; set; }
        public virtual ICollection<Items> Items { get; set; }
        public virtual ICollection<TipoBarraCategoriaItem> TipoBarraCategoriaItem { get; set; }
        public virtual ICollection<TipoCateringTiempoProductoItem> TipoCateringTiempoProductoItem { get; set; }
    }
}
