//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.CostoAmbientacion = new HashSet<CostoAmbientacion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int LocacionId { get; set; }
        public int SectorId { get; set; }
        public int CaracteristicaId { get; set; }
        public int SegmentoId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Caracteristicas Caracteristicas { get; set; }
        public virtual Locaciones Locaciones { get; set; }
        public virtual Segmentos Segmentos { get; set; }
        public virtual ICollection<CostoAmbientacion> CostoAmbientacion { get; set; }
    }
}
