//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comandas
    {
        public int Id { get; set; }
        public int PresupuestoId { get; set; }
        public Nullable<System.DateTime> fechaEvento { get; set; }
        public string Locacion { get; set; }
        public string HorarioLlegada { get; set; }
        public string HorarioInicio { get; set; }
        public string HorarioFin { get; set; }
        public string TipoEvento { get; set; }
        public string TipoExperiencia { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Empresa { get; set; }
        public string Organizador { get; set; }
        public string Maitre { get; set; }
        public string Coordinador { get; set; }
        public string JefeProducto { get; set; }
        public Nullable<int> Adultos { get; set; }
        public Nullable<int> Menores3 { get; set; }
        public Nullable<int> Menores3y8 { get; set; }
        public Nullable<int> Adolescentes { get; set; }
        public int EstadoId { get; set; }
    }
}
