//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionIva
    {
        public CondicionIva()
        {
            this.Proveedores = new HashSet<Proveedores>();
            this.TipoComprobantes = new HashSet<TipoComprobantes>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<TipoComprobantes> TipoComprobantes { get; set; }
    }
}
