//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionCateringTecnica
    {
        public int Id { get; set; }
        public int SegmentoId { get; set; }
        public int CaracteristicaId { get; set; }
        public int DuracionId { get; set; }
        public int MomentoDiaId { get; set; }
        public int TipoCateringId { get; set; }
        public Nullable<int> TipoServicioId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Caracteristicas Caracteristicas { get; set; }
        public virtual MomentosDias MomentosDias { get; set; }
        public virtual Segmentos Segmentos { get; set; }
        public virtual TipoCatering TipoCatering { get; set; }
        public virtual TipoServicios TipoServicios { get; set; }
        public virtual DuracionEvento DuracionEvento { get; set; }
    }
}
