//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_Log
    {
        public int Id { get; set; }
        public int CuentaId { get; set; }
        public string Descripcion { get; set; }
        public double SaldoAnterior { get; set; }
        public double SaldoActual { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> PagoClienteId { get; set; }
        public Nullable<int> PagoProveedorId { get; set; }
        public Nullable<int> TipoMovimientoId { get; set; }
        public Nullable<double> TipoCambio { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
