//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_Log
    {
        public int Id { get; set; }
        public int CuentaId { get; set; }
        public string Descripcion { get; set; }
        public double SaldoAnterior { get; set; }
        public double SaldoActual { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> PagoClienteId { get; set; }
        public Nullable<int> PagoProveedorId { get; set; }
        public Nullable<int> TipoMovimientoId { get; set; }
        public Nullable<double> TipoCambio { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
