//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public Cuentas()
        {
            this.ComprobantesProveedores = new HashSet<ComprobantesProveedores>();
            this.Cuentas_Log = new HashSet<Cuentas_Log>();
            this.PagosProveedores = new HashSet<PagosProveedores>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoCuenta { get; set; }
        public int MonedaId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual ICollection<ComprobantesProveedores> ComprobantesProveedores { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ICollection<Cuentas_Log> Cuentas_Log { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual ICollection<PagosProveedores> PagosProveedores { get; set; }
    }
}
