//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuracionEvento
    {
        public DuracionEvento()
        {
            this.ConfiguracionCateringTecnica = new HashSet<ConfiguracionCateringTecnica>();
            this.Presupuestos = new HashSet<Presupuestos>();
            this.TiposBarras = new HashSet<TiposBarras>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CantidadHoras { get; set; }
    
        public virtual ICollection<ConfiguracionCateringTecnica> ConfiguracionCateringTecnica { get; set; }
        public virtual ICollection<Presupuestos> Presupuestos { get; set; }
        public virtual ICollection<TiposBarras> TiposBarras { get; set; }
    }
}
