//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosPresupuestosAprobados
    {
        public int Id { get; set; }
        public int PresupuestoId { get; set; }
        public Nullable<int> CoordinadorId { get; set; }
        public Nullable<int> CoordinadorBisId { get; set; }
        public string HoraIngresoCoordinador1 { get; set; }
        public string HoraIngresoCoordinador2 { get; set; }
        public Nullable<int> JefeSalonId { get; set; }
        public Nullable<int> JefeCocinaId { get; set; }
        public Nullable<int> JefeBarraId { get; set; }
        public Nullable<int> JefeOperacionId { get; set; }
        public Nullable<int> JefeLogisticaId { get; set; }
        public Nullable<int> OrganizadorId { get; set; }
        public Nullable<int> ResponsableLogisticaArmadoId { get; set; }
        public Nullable<int> ResponsableLogisticaDesarmadoId { get; set; }
    
        public virtual Presupuestos Presupuestos { get; set; }
    }
}
