//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public Empleados()
        {
            this.DegustacionDetalle = new HashSet<DegustacionDetalle>();
            this.EmpleadoDepartamentos = new HashSet<EmpleadoDepartamentos>();
            this.Eventos = new HashSet<Eventos>();
            this.LiquidacionHorasPersonal_Detalle = new HashSet<LiquidacionHorasPersonal_Detalle>();
            this.ObjetivosEmpleados = new HashSet<ObjetivosEmpleados>();
            this.OrganizacionPresupuestosArchivos = new HashSet<OrganizacionPresupuestosArchivos>();
        }
    
        public int Id { get; set; }
        public string ApellidoNombre { get; set; }
        public string Nombre { get; set; }
        public int NroLegajo { get; set; }
        public string Mail { get; set; }
        public string MailLaboral { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> NroDocumento { get; set; }
        public string Cuil { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string DireccionLegal { get; set; }
        public int LocalidadId { get; set; }
        public Nullable<int> CiudadLegalId { get; set; }
        public string CP { get; set; }
        public string CPLegal { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoMovil { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string TelefonoFijoLaboral { get; set; }
        public string CelularFijoLaboral { get; set; }
        public bool UsaPc { get; set; }
        public string NroPc { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public int SectorEmpresaId { get; set; }
        public int TipoEmpleadoId { get; set; }
        public string HorarioDesde { get; set; }
        public string HorarioHasta { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public Nullable<double> Premio { get; set; }
        public Nullable<double> SAC { get; set; }
        public string Observaciones { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Ciudades Ciudades1 { get; set; }
        public virtual ICollection<DegustacionDetalle> DegustacionDetalle { get; set; }
        public virtual ICollection<EmpleadoDepartamentos> EmpleadoDepartamentos { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual SectoresEmpresa SectoresEmpresa { get; set; }
        public virtual TipoEmpleados TipoEmpleados { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual ICollection<LiquidacionHorasPersonal_Detalle> LiquidacionHorasPersonal_Detalle { get; set; }
        public virtual ICollection<ObjetivosEmpleados> ObjetivosEmpleados { get; set; }
        public virtual ICollection<OrganizacionPresupuestosArchivos> OrganizacionPresupuestosArchivos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
