//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosporPresupuestos
    {
        public long NroComprobante { get; set; }
        public string TIPOMOVIMIENTO { get; set; }
        public string CENTROCOSTO { get; set; }
        public double Importe { get; set; }
        public string IMPUESTO { get; set; }
        public double ValorImpuesto { get; set; }
        public double ValorImpuestoInterno { get; set; }
        public Nullable<int> PresupuestoId { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoNombre { get; set; }
        public string Leyenda { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
