//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosporPresupuestos
    {
        public long NroComprobante { get; set; }
        public string TIPOMOVIMIENTO { get; set; }
        public string CENTROCOSTO { get; set; }
        public double Importe { get; set; }
        public string IMPUESTO { get; set; }
        public double ValorImpuesto { get; set; }
        public double ValorImpuestoInterno { get; set; }
        public Nullable<int> PresupuestoId { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoNombre { get; set; }
        public string Leyenda { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
