//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuestos
    {
        public Impuestos()
        {
            this.ComprobantesProveedores_Detalles = new HashSet<ComprobantesProveedores_Detalles>();
            this.TipoComprobante_Impuestos = new HashSet<TipoComprobante_Impuestos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Porcentaje { get; set; }
    
        public virtual ICollection<ComprobantesProveedores_Detalles> ComprobantesProveedores_Detalles { get; set; }
        public virtual ICollection<TipoComprobante_Impuestos> TipoComprobante_Impuestos { get; set; }
    }
}
