//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_Unidades
    {
        public INVENTARIO_Unidades()
        {
            this.INVENTARIO_Producto = new HashSet<INVENTARIO_Producto>();
            this.INVENTARIO_Producto1 = new HashSet<INVENTARIO_Producto>();
            this.INVENTARIO_Recetas = new HashSet<INVENTARIO_Recetas>();
            this.INVENTARIO_UnidadesConversion = new HashSet<INVENTARIO_UnidadesConversion>();
            this.INVENTARIO_UnidadesConversion1 = new HashSet<INVENTARIO_UnidadesConversion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
    
        public virtual ICollection<INVENTARIO_Producto> INVENTARIO_Producto { get; set; }
        public virtual ICollection<INVENTARIO_Producto> INVENTARIO_Producto1 { get; set; }
        public virtual ICollection<INVENTARIO_Recetas> INVENTARIO_Recetas { get; set; }
        public virtual ICollection<INVENTARIO_UnidadesConversion> INVENTARIO_UnidadesConversion { get; set; }
        public virtual ICollection<INVENTARIO_UnidadesConversion> INVENTARIO_UnidadesConversion1 { get; set; }
    }
}
