//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_Producto
    {
        public INVENTARIO_Producto()
        {
            this.INVENTARIO_Movimiento_Producto = new HashSet<INVENTARIO_Movimiento_Producto>();
            this.INVENTARIO_ProductoDeposito = new HashSet<INVENTARIO_ProductoDeposito>();
            this.INVENTARIO_Recetas = new HashSet<INVENTARIO_Recetas>();
            this.INVENTARIO_Recetas1 = new HashSet<INVENTARIO_Recetas>();
        }
    
        public int Id { get; set; }
        public int RubroId { get; set; }
        public string Codigo { get; set; }
        public string CodigoBarra { get; set; }
        public string Descripcion { get; set; }
        public double CantidadNominal { get; set; }
        public double Cantidad { get; set; }
        public double Costo { get; set; }
        public int UnidadId { get; set; }
        public int UnidadPresentacionId { get; set; }
        public int UnidadMedidaConversionId { get; set; }
        public Nullable<int> TipoMovimientoId { get; set; }
        public Nullable<int> CentroCostoId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<INVENTARIO_Movimiento_Producto> INVENTARIO_Movimiento_Producto { get; set; }
        public virtual INVENTARIO_Unidades INVENTARIO_Unidades { get; set; }
        public virtual INVENTARIO_Unidades INVENTARIO_Unidades1 { get; set; }
        public virtual INVENTARIO_UnidadesConversion INVENTARIO_UnidadesConversion { get; set; }
        public virtual Rubros Rubros { get; set; }
        public virtual ICollection<INVENTARIO_ProductoDeposito> INVENTARIO_ProductoDeposito { get; set; }
        public virtual ICollection<INVENTARIO_Recetas> INVENTARIO_Recetas { get; set; }
        public virtual ICollection<INVENTARIO_Recetas> INVENTARIO_Recetas1 { get; set; }
    }
}
