//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.AdicionalesItems = new HashSet<AdicionalesItems>();
            this.ItemDetalleRatio = new HashSet<ItemDetalleRatio>();
            this.ProductosCateringItems = new HashSet<ProductosCateringItems>();
        }
    
        public int Id { get; set; }
        public string Detalle { get; set; }
        public int CategoriaItemId { get; set; }
        public double Costo { get; set; }
        public double Margen { get; set; }
        public double Precio { get; set; }
        public int EstadoId { get; set; }
    
        public virtual ICollection<AdicionalesItems> AdicionalesItems { get; set; }
        public virtual CategoriasItem CategoriasItem { get; set; }
        public virtual ICollection<ItemDetalleRatio> ItemDetalleRatio { get; set; }
        public virtual ICollection<ProductosCateringItems> ProductosCateringItems { get; set; }
    }
}
