//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionHorasPersonal
    {
        public LiquidacionHorasPersonal()
        {
            this.LiquidacionHorasPersonal_Detalle = new HashSet<LiquidacionHorasPersonal_Detalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EstadoId { get; set; }
        public int PresupuestoId { get; set; }
        public System.DateTime FechaCreate { get; set; }
        public Nullable<System.DateTime> FechaUpdate { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.DateTime> FechaDelete { get; set; }
    
        public virtual ICollection<LiquidacionHorasPersonal_Detalle> LiquidacionHorasPersonal_Detalle { get; set; }
    }
}
