//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public Monedas()
        {
            this.ConversionMonedas = new HashSet<ConversionMonedas>();
            this.ConversionMonedas1 = new HashSet<ConversionMonedas>();
            this.Cuentas = new HashSet<Cuentas>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
    
        public virtual ICollection<ConversionMonedas> ConversionMonedas { get; set; }
        public virtual ICollection<ConversionMonedas> ConversionMonedas1 { get; set; }
        public virtual ICollection<Cuentas> Cuentas { get; set; }
    }
}
