//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public Monedas()
        {
            this.ConversionMonedas = new HashSet<ConversionMonedas>();
            this.ConversionMonedas1 = new HashSet<ConversionMonedas>();
            this.Cuentas = new HashSet<Cuentas>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
    
        public virtual ICollection<ConversionMonedas> ConversionMonedas { get; set; }
        public virtual ICollection<ConversionMonedas> ConversionMonedas1 { get; set; }
        public virtual ICollection<Cuentas> Cuentas { get; set; }
    }
}
