//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerEventosSeguimiento
    {
        public int EventoId { get; set; }
        public int ClienteId { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoNombreCliente { get; set; }
        public string Mail { get; set; }
        public string Celular { get; set; }
        public string ApellidoNombre { get; set; }
        public string Descripcion { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EmpleadoId { get; set; }
        public string Comentario { get; set; }
    }
}
