//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerClientes
    {
        public int Id { get; set; }
        public string ApellidoNombre { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<System.DateTime> FechaContacto { get; set; }
        public Nullable<int> ComollegoId { get; set; }
        public string ComoLlegoOtro { get; set; }
        public string Comentario { get; set; }
        public string RazonSocial { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<int> EmpleadoAsignadoId { get; set; }
        public string Ejecutivo { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
    }
}
