//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerDatosParaPresupuesto
    {
        public int ClienteId { get; set; }
        public string ApellidoNombre { get; set; }
        public string Mail { get; set; }
        public string Celular { get; set; }
        public int SegmentoId { get; set; }
        public string Segmento { get; set; }
        public int CaracteristicaId { get; set; }
        public string Caracteristica { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Sector { get; set; }
        public int TipoEventoId { get; set; }
        public string TipoEvento { get; set; }
        public int LocacionId { get; set; }
        public string Locacion { get; set; }
        public string TipoLocacion { get; set; }
        public int JornadaId { get; set; }
        public string Jornada { get; set; }
        public Nullable<int> CantidadInicialInvitados { get; set; }
        public Nullable<int> CantidadInvitadosMenores3 { get; set; }
        public Nullable<int> CantidadInvitadosMenores3y8 { get; set; }
        public Nullable<int> CantidadInvitadosAdolecentes { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string HorarioEvento { get; set; }
        public string HorarioArmado { get; set; }
        public string HoraFinalizado { get; set; }
        public string Comentario { get; set; }
        public int EventoId { get; set; }
        public int EmpleadoId { get; set; }
        public string Ejecutivo { get; set; }
        public System.DateTime FechaContacto { get; set; }
        public Nullable<int> PresupuestoId { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<double> PrecioTotal { get; set; }
        public Nullable<double> PrecioPorPersona { get; set; }
        public string ComentarioPresupuesto { get; set; }
        public Nullable<System.DateTime> FechaPresupuesto { get; set; }
        public string LocacionOtra { get; set; }
    }
}
