//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerAdiciones
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public int RubroId { get; set; }
        public string Rubro { get; set; }
        public int EstadoId { get; set; }
        public string EstadoDescripcion { get; set; }
        public string RequiereCantidad { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public Nullable<double> Costo { get; set; }
    }
}
