//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoDetalle_Log
    {
        public int Id { get; set; }
        public int PresupuestoDetalleId { get; set; }
        public int EstadoId { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Orden { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual PresupuestoDetalle PresupuestoDetalle { get; set; }
    }
}
