//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresExternos
    {
        public int Id { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> DIA { get; set; }
        public string HorarioEvento { get; set; }
        public string HoraFinalizado { get; set; }
        public string Ejecutivo { get; set; }
        public Nullable<int> Total_Invitados { get; set; }
        public string Locacion { get; set; }
        public string Proveedor { get; set; }
        public string Rubro { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
    }
}
