//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboEventoPresupuesto
    {
        public int Id { get; set; }
        public int ReciboId { get; set; }
        public int EventoId { get; set; }
        public Nullable<int> PresupuestoId { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
        public virtual Recibos Recibos { get; set; }
    }
}
