//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteEventosCobranzas
    {
        public int PresupuestoId { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> DIA { get; set; }
        public Nullable<int> Total_Invitados { get; set; }
        public string Unidad_de_Negocio { get; set; }
        public string UnidadNegocioAdicional { get; set; }
        public string PrecioSeleccionado { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoNombre { get; set; }
        public string Locacion { get; set; }
        public Nullable<int> ANIOSENIA { get; set; }
        public Nullable<int> MESSENIA { get; set; }
        public Nullable<int> DIASENIA { get; set; }
        public string Ejecutivo { get; set; }
        public double Comision { get; set; }
        public double Cannon { get; set; }
        public double Logistica { get; set; }
        public double Fee { get; set; }
        public double Organizador { get; set; }
        public double Descuentos { get; set; }
        public double Incrementos { get; set; }
        public Nullable<double> COSTO_TOTAL { get; set; }
        public Nullable<double> PRECIO_TOTAL { get; set; }
        public Nullable<double> TOTAL_PRESUPUESTO_SIN_INDEXACION { get; set; }
        public double TOTAL_PAGADO { get; set; }
        public Nullable<double> VALOR_COMISIONABLE { get; set; }
    }
}
