//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsablesEventos
    {
        public int PresupuestoId { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string HorarioEvento { get; set; }
        public string HoraFinalizado { get; set; }
        public string Caracteristica { get; set; }
        public string Segmento { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoNombre { get; set; }
        public string LOCACION { get; set; }
        public Nullable<int> Total_Invitados { get; set; }
        public string Resp__Cocina { get; set; }
        public string Resp__Barra { get; set; }
        public string Resp__Logistica { get; set; }
        public string Resp__Operaciones { get; set; }
        public string Resp__Salon { get; set; }
        public string Coordinador_1 { get; set; }
        public string Coordinador_2 { get; set; }
        public string Organizador { get; set; }
        public string Resp__Logistica_Armado { get; set; }
        public string Resp__Logistica_Desarmado { get; set; }
        public Nullable<int> OrganizadorId { get; set; }
        public Nullable<int> Coordinador1Id { get; set; }
        public Nullable<int> Coordinador2Id { get; set; }
        public string HoraIngresoCoordinador1 { get; set; }
        public string HoraIngresoCoordinador2 { get; set; }
    }
}
