//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLogistica
    {
        public TipoLogistica()
        {
            this.CostoLogistica = new HashSet<CostoLogistica>();
        }
    
        public int Id { get; set; }
        public string Concepto { get; set; }
    
        public virtual ICollection<CostoLogistica> CostoLogistica { get; set; }
    }
}
