//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEmpleados
    {
        public TipoEmpleados()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> SectorEmpresaId { get; set; }
    
        public virtual ICollection<Empleados> Empleados { get; set; }
        public virtual SectoresEmpresa SectoresEmpresa { get; set; }
    }
}
