//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCateringTiempoProductoItem
    {
        public int Id { get; set; }
        public int TipoCateringId { get; set; }
        public int TiempoId { get; set; }
        public Nullable<int> ProductoCateringId { get; set; }
        public Nullable<int> CategoriaItemId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual CategoriasItem CategoriasItem { get; set; }
        public virtual ProductosCatering ProductosCatering { get; set; }
        public virtual Tiempos Tiempos { get; set; }
        public virtual TipoCatering TipoCatering { get; set; }
    }
}
