//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposBarras
    {
        public TiposBarras()
        {
            this.CostoBarra = new HashSet<CostoBarra>();
            this.TipoBarraCategoriaItem = new HashSet<TipoBarraCategoriaItem>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int SegmentoId { get; set; }
        public int DuracionId { get; set; }
        public string RangoEtareo { get; set; }
    
        public virtual ICollection<CostoBarra> CostoBarra { get; set; }
        public virtual DuracionEvento DuracionEvento { get; set; }
        public virtual Segmentos Segmentos { get; set; }
        public virtual ICollection<TipoBarraCategoriaItem> TipoBarraCategoriaItem { get; set; }
    }
}
