//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAmbientHouse.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicios
    {
        public TipoServicios()
        {
            this.ConfiguracionCateringTecnica = new HashSet<ConfiguracionCateringTecnica>();
            this.CostoTecnica = new HashSet<CostoTecnica>();
            this.TipoServicioAdicional = new HashSet<TipoServicioAdicional>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int RubroId { get; set; }
    
        public virtual ICollection<ConfiguracionCateringTecnica> ConfiguracionCateringTecnica { get; set; }
        public virtual ICollection<CostoTecnica> CostoTecnica { get; set; }
        public virtual ICollection<TipoServicioAdicional> TipoServicioAdicional { get; set; }
        public virtual UnidadesNegocios UnidadesNegocios { get; set; }
    }
}
